name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.Java }}
          distribution: "temurin"
          cache: "gradle"
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: jmh
